/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * <p>This source code is licensed under the MIT license found in the LICENSE file in the root
 * directory of this source tree.
 *
 * <p>Generated by an internal genrule from Flow types.
 *
 * @generated
 * @nolint
 */

package com.turbomoduleplayground.turbomodule.spec;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReactModuleWithSpec;
import com.facebook.react.common.build.ReactBuildConfig;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.annotation.Nullable;

public abstract class TurboModuleSpec extends ReactContextBaseJavaModule implements ReactModuleWithSpec, TurboModule {

    public TurboModuleSpec(ReactApplicationContext reactContext) {
        super(reactContext);
    }

//    protected abstract Map<String, Object> getTypedExportedConstants();

    // @ReactMethod
    // public abstract @Nullable Map<String, Object> getConstants();

    @ReactMethod(isBlockingSynchronousMethod = true)
    public abstract @Nullable String language();

    @ReactMethod(isBlockingSynchronousMethod = true)
    public abstract @Nullable String greeting();
}